#ifndef _HAL_COMPONENT_TYPES_H_
#define _HAL_COMPONENT_TYPES_H_

#include "component_position.c"

//Component types
#define COMPONENT_TYPE_POSITION 1
#define COMPONENT_TYPE_VELOCITY 2
#define COMPONENT_TYPE_SPRITE 3
#define COMPONENT_TYPE_COLLIDER 4
#define COMPONENT_TYPE_HEALTH 5
#define COMPONENT_TYPE_AI 6
#define COMPONENT_TYPE_PLAYER 7
#define COMPONENT_TYPE_INPUT 8
#define COMPONENT_TYPE_ANIMATION 9
#define COMPONENT_TYPE_SOUND 10
#define COMPONENT_TYPE_TEXT 11
#define COMPONENT_TYPE_TIMER 12
#define COMPONENT_TYPE_CAMERA 13
#define COMPONENT_TYPE_LIGHT 14
#define COMPONENT_TYPE_PARTICLE 15
#define COMPONENT_TYPE_PHYSICS 16
#define COMPONENT_TYPE_SCRIPT 17
#define COMPONENT_TYPE_PATH 18
#define COMPONENT_TYPE_BUTTON 19
#define COMPONENT_TYPE_SLIDER 20



#endif